#
# Copyright (c) 2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
---
apiVersion: v1
kind: Template
metadata:
  name: che-devfile-registry
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: che
      component: devfile-registry
    name: devfile-registry
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: che
        component: devfile-registry
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: che
          component: devfile-registry
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: "${PULL_POLICY}"
          name: devfile-registry
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /devfiles/
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /devfiles/
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: devfile-registry
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    selector:
      app: che
      component: devfile-registry
- apiVersion: v1
  kind: Route
  metadata:
    name: devfile-registry
  spec:
    to:
      kind: Service
      name: devfile-registry
parameters:
- name: IMAGE
  value: quay.io/eclipse/che-devfile-registry
  displayName: Eclipse Che devfile registry image
  description: Che devfile registry Docker image. Defaults to quay.io/eclipse/che-devfile-registry.
- name: IMAGE_TAG
  value: latest
  displayName: Eclipse Che devfile registry version
  description: Eclipse Che devfile registry version which defaults to latest
- name: MEMORY_LIMIT
  value: 256Mi
  displayName: Memory Limit
  description: Maximum amount of memory the container can use. Defaults 256Mi
- name: PULL_POLICY
  value: Always
  displayName: Eclipse Che devfile registry image pull policy
  description: Always pull by default. Can be IfNotPresent
labels:
  app: che
  component: devfile-registry
  template: che-devfile-registry
